### ISSUE TITLE
ListLengthResource undefined

### ISSUE THREAD

**Issue by superstator** [dlemstra/Magick.NET#165]
Since merging the latest changes, I get an error while building Linux native libraries:

    Magick.NET\Source\Magick.NET.Native\ResourceLimits.c(38,33): error : 'ListLengthResource' undeclared

Where is this defined? I couldn't find that string anywhere under Magick.NET\Source, is there maybe a header file not checked in somewhere?

**Comment by superstator** [comment]
Nevermind, my rearranging of the docker build changed some paths.
